name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
      mod: ${{ steps.vars.outputs.mod }}
    steps:
      - name: Get the Release version tag and mod name
        id: vars
        # Fail this and dependant jobs on invalid tag name
        run: |-
          if [[ "$GITHUB_REF_NAME" =~ ^v([0-9\.]+)-(.+)$ ]]; then
            echo "tag=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "mod=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          else
            echo '::error::invalid release tag "${{ github.ref }}", required schema: v1.0.0-ModName'
            exit 1
          fi

  publish:
    needs: vars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v5
      - name: Install mono and xbuild
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: git mono-complete mono-xbuild

      - name: Update const string BepinEx version field
        run: sed -i 's/"0.0.1"/"${{needs.vars.outputs.tag}}"/g' ${{needs.vars.outputs.mod}}/${{needs.vars.outputs.mod}}.cs

      - name: Check file existence
        id: check_files
        run: echo "exists=$((test -f ${{needs.vars.outputs.mod}}/manifest.json && echo true) || echo false)" >> $GITHUB_OUTPUT

      - name: Update manifest/json version field
        run: sed -i 's/"0.0.1"/"${{needs.vars.outputs.tag}}"/g' ${{needs.vars.outputs.mod}}/manifest.json
        if: steps.check_files.outputs.exists == 'true'

      - name: Build and Create the package
        run: xbuild ValheimMod.sln /t:${{needs.vars.outputs.mod}} /p:Configuration=Release /p:Version=${{needs.vars.outputs.tag}} /p:OutputPath=..

      # Package for Thunderstore
      - uses: papeloto/action-zip@v1
        with:
          files: ${{needs.vars.outputs.mod}}.dll ${{needs.vars.outputs.mod}}/icon.png ${{needs.vars.outputs.mod}}/manifest.json ${{needs.vars.outputs.mod}}/README.md
          dest: ${{needs.vars.outputs.mod}}_${{needs.vars.outputs.tag}}_thunderstore.zip
        if: steps.check_files.outputs.exists == 'true'

      # Package for Nexus Mods
      - uses: papeloto/action-zip@v1
        with:
          files: ${{needs.vars.outputs.mod}}.dll
          dest: ${{needs.vars.outputs.mod}}_${{ needs.vars.outputs.tag }}_nexusmods.zip

      - name: Change Log
        id: changelog
        run: |
          git fetch --tags --force # Retrieve annotated tags. THIS TRICK REALLY HELPS
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          git tag -l ${GITHUB_REF:10} --format='%(contents:body)' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          body: |
            Change Log
            ${{ env.CHANGELOG }}
          name: Release ${{needs.vars.outputs.mod}} ${{needs.vars.outputs.tag}}
          draft: false
          prerelease: false
          files: |-
            ${{needs.vars.outputs.mod}}*.zip

      # - name: Install NexusUploader
      #   run: dotnet tool install -g NexusUploader
      #
      #- name: Upload
      #  run: |
      #    unex upload 504 ValheimLib_release.zip -v ${{ needs.vars.outputs.tag }}
      #  env:
      #    UNEX_APIKEY: ${{ secrets.NEXUS_API_KEY }}
      #    UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
      #    UNEX_DEBUG: true
      #    UNEX_FILENAME: ValheimLib
      #    UNEX_GAME: valheim

  variants:
    if: endsWith(github.ref, 'EquipWheel')
    needs: vars
    strategy:
      matrix:
        mod: [EquipWheelTwo, EquipWheelThree, EquipWheelFour]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5

      - name: Install mono and xbuild
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: git mono-complete mono-xbuild

      - name: Update const string BepinEx version field
        run: sed -i 's/"0.0.1"/"${{needs.vars.outputs.tag}}"/g' EquipWheel/EquipWheel.cs

      - name: Build and Create the package
        run: xbuild ValheimMod.sln /t:${{matrix.mod}} /p:Configuration=Release /p:Version=${{needs.vars.outputs.tag}} /p:OutputPath=..

      - uses: actions/upload-artifact@v4
        with:
          name: more-equipwheels-${{matrix.mod}}
          path: ${{matrix.mod}}.dll

  bundle-variants:
    if: endsWith(github.ref, 'EquipWheel')
    runs-on: ubuntu-latest
    needs:
      - vars
      - publish
      - variants

    steps:
      - uses: actions/checkout@v5

      - name: Update const string version field (1/2)
        run: sed -i 's/"0.0.1"/"${{needs.vars.outputs.tag}}"/g' MoreEquipWheels/manifest.json

      - name: Update const string version field (2/2)
        run: sed -i 's/"virtuaCode-EquipWheel-0.0.1"/"virtuaCode-EquipWheel-${{needs.vars.outputs.tag}}"/g' MoreEquipWheels/manifest.json

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          pattern: more-equipwheels-*
          merge-multiple: true

      - uses: papeloto/action-zip@v1
        with:
          files: EquipWheelTwo.dll EquipWheelThree.dll EquipWheelFour.dll MoreEquipWheels/icon.png MoreEquipWheels/manifest.json MoreEquipWheels/README.md
          dest: More_EquipWheels_${{ needs.vars.outputs.tag }}_thunderstore.zip

      - uses: papeloto/action-zip@v1
        with:
          files: EquipWheelTwo.dll EquipWheelThree.dll EquipWheelFour.dll
          dest: More_EquipWheels_${{ needs.vars.outputs.tag }}_nexusmods.zip

      - name: Upload Release Asset
        id: upload-asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |-
            More_EquipWheels*.zip
